interface Ifrases {
    id: number
    categoria: string
    selected: boolean
    frases: string[]
}

export type Frases = Ifrases[]

const frasesMotivacionais = [
    "Acredite em você mesmo e tudo será possível.",
    "O único modo de fazer um excelente trabalho é amar o que você faz.",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "A vida é 10% o que acontece comigo e 90% como eu reajo a isso.",
    "A única maneira de fazer um ótimo trabalho é amar o que você faz.",
    "Se você traçar metas absurdamente altas e falhar, seu fracasso será muito melhor que o sucesso de todos.",
    "Acredite em si mesmo e em tudo que você é. Saiba que há algo dentro de você que é maior do que qualquer obstáculo.",
    "A única limitação para o seu sucesso é a sua própria imaginação.",
    "O que você realiza depende do que você acredita ser possível.",
    "O segredo para conseguir ir mais longe é começar.",
    "Se você não está disposto a arriscar, esteja disposto a uma vida comum.",
    "A vida é o que acontece quando você está ocupado fazendo outros planos.",
    "Viver é a coisa mais rara do mundo. A maioria das pessoas apenas existe.",
    "A jornada de mil quilômetros começa com um passo.",
    "Apenas faça o que é certo. O que é certo para você, de qualquer maneira.",
    "Não espere. O tempo nunca será o certo.",
    "Não tenha medo de desistir do bom para perseguir o ótimo.",
    "A única maneira de fazer um excelente trabalho é amar o que você faz.",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "A vida é 10% o que acontece comigo e 90% como eu reajo a isso.",
    "Se você não está disposto a arriscar, esteja disposto a uma vida comum.",
    "A vida é o que acontece quando você está ocupado fazendo outros planos.",
    "Acredite em si mesmo e em tudo que você é. Saiba que há algo dentro de você que é maior do que qualquer obstáculo.",
    "Viver é a coisa mais rara do mundo. A maioria das pessoas apenas existe.",
    "A jornada de mil quilômetros começa com um passo.",
    "Apenas faça o que é certo. O que é certo para você, de qualquer maneira.",
    "Acredite em si mesmo e tudo que você é. Saiba que há algo dentro de você que é maior do que qualquer obstáculo.",
    "Não espere. O tempo nunca será o certo.",
    "Não tenha medo de desistir do bom para perseguir o ótimo.",
    "A vida é 10% o que acontece comigo e 90% como eu reajo a isso.",
    "O único modo de fazer um excelente trabalho é amar o que você faz.",
    "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
    "A vida é 10% o que acontece comigo e 90% como eu reajo a isso.",
    "A única maneira de fazer um ótimo trabalho é amar o que você faz.",
    "Se você traçar metas absurdamente altas e falhar, seu fracasso será muito melhor que o sucesso de todos.",
    "Acredite em si mesmo e em tudo que você é. Saiba que há algo dentro de você que é maior do que qualquer obstáculo.",
    "A única limitação para o seu sucesso é a sua própria imaginação.",
    "O que você realiza depende do que você acredita ser possível.",
    "O segredo para conseguir ir mais longe é começar.",
    "Se você não está disposto a arriscar, esteja disposto a uma vida comum.",
    "O único jeito de fazer um excelente trabalho é amar o que você faz.",
    "A vida é o que acontece quando você está ocupado fazendo outros planos.",
    "Acredite em si mesmo e em tudo que você é. Saiba que há algo dentro de você que é maior do que qualquer obstáculo.",
    "Viver é a coisa mais rara do mundo. A maioria das pessoas apenas existe.",
    "A jornada de mil quilômetros começa com um passo.",
    "Apenas faça o que é certo. O que é certo para você, de qualquer maneira.",
    "Acredite em si mesmo e tudo que você é. Saiba que há algo dentro de você que é maior do que qualquer obstáculo.",
    "Não espere. O tempo nunca será o certo.",
    "Não tenha medo de desistir do bom para perseguir o ótimo.",
    "Nós nos tornamos o que pensamos."
]

const frasesBomDia = [
    "Bom dia! Aproveite o novo dia com um sorriso no rosto.",
    "Que seu dia seja iluminado e cheio de alegrias. Bom dia!",
    "A cada manhã, a vida se renova. Aproveite a dádiva de um novo dia. Bom dia!",
    "Bom dia! Que as boas energias te acompanhem durante todo o dia.",
    "Levante-se e vá em busca dos seus sonhos. Bom dia!",
    "Que o dia de hoje seja melhor que ontem e pior que amanhã. Bom dia!",
    "Bom dia! A vida é um presente, aproveite-a ao máximo.",
    "Comece o dia com gratidão e tudo de bom virá até você. Bom dia!",
    "Que a luz do sol ilumine seu caminho hoje e sempre. Bom dia!",
    "Desejo que o seu dia seja repleto de sorrisos e momentos felizes. Bom dia!",
    "Bom dia! Hoje é o dia perfeito para ser feliz.",
    "Aproveite cada segundo do seu dia. Bom dia!",
    "Que o dia de hoje traga boas notícias e belas surpresas. Bom dia!",
    "A vida é feita de oportunidades. Aproveite cada uma delas. Bom dia!",
    "Bom dia! Que seu dia seja abençoado e cheio de realizações.",
    "Comece o dia com um coração grato e tudo será possível. Bom dia!",
    "Que o dia comece bem e termine ainda melhor. Bom dia!",
    "Bom dia! A vida é curta, aproveite cada momento.",
    "Que a alegria invada o seu coração neste novo dia. Bom dia!",
    "A cada novo amanhecer, uma nova chance de ser feliz. Bom dia!",
    "Bom dia! Que o dia seja leve e cheio de boas energias.",
    "Levante com o sol e vá em busca dos seus sonhos. Bom dia!",
    "Aproveite o dia e faça dele algo incrível. Bom dia!",
    "Bom dia! Que o dia seja produtivo e cheio de realizações.",
    "A vida é um presente, aproveite-a ao máximo. Bom dia!",
    "Que cada manhã traga novas oportunidades. Bom dia!",
    "Bom dia! Que a felicidade faça morada em seu coração.",
    "Aproveite cada segundo do seu dia. Bom dia!",
    "Que o dia de hoje seja repleto de boas surpresas. Bom dia!",
    "Bom dia! A vida é feita de momentos especiais, aproveite-os.",
    "Comece o dia com um sorriso no rosto e o coração cheio de gratidão. Bom dia!",
    "Que o dia comece com boas notícias e termine com ótimas realizações. Bom dia!",
    "Bom dia! Que a luz do sol ilumine o seu caminho hoje e sempre.",
    "A vida é feita de escolhas, escolha ser feliz. Bom dia!",
    "Que o dia de hoje seja repleto de bênçãos. Bom dia!",
    "Bom dia! Desperte para a vida e faça cada momento valer a pena.",
    "Aproveite o dia com alegria e entusiasmo. Bom dia!",
    "Que o dia de hoje seja melhor que ontem e pior que amanhã. Bom dia!",
    "Bom dia! Que o amor e a paz guiem o seu caminho.",
    "Comece o dia com o pé direito e vá em busca dos seus sonhos. Bom dia!",
    "Que o dia de hoje traga muita positividade e realizações. Bom dia!",
    "Bom dia! Cada dia é uma nova oportunidade para ser feliz.",
    "A vida é uma dádiva, aproveite-a ao máximo. Bom dia!",
    "Que a alegria de viver transborde em seu coração. Bom dia!",
    "Bom dia! Que o dia seja repleto de sorrisos e momentos felizes.",
    "Comece o dia com gratidão e tudo de bom virá até você. Bom dia!",
    "Que o dia de hoje seja abençoado e cheio de alegrias. Bom dia!",
    "Bom dia! A cada manhã, a vida se renova. Aproveite a dádiva de um novo dia.",
    "Que seu dia seja iluminado e cheio de boas energias. Bom dia!",
    "A vida é feita de oportunidades, aproveite cada uma delas. Bom dia!",
    "Bom dia! Que o dia comece bem e termine ainda melhor.",
    "Aproveite cada segundo do seu dia. Bom dia!",
    "Que o dia de hoje traga boas notícias e belas surpresas. Bom dia!",
    "Bom dia! A vida é curta, aproveite cada momento.",
    "Que a alegria invada o seu coração neste novo dia. Bom dia!",
    "A cada novo amanhecer, uma nova chance de ser feliz. Bom dia!",
    "Bom dia! Que o dia seja leve e cheio de boas energias.",
    "Levante com o sol e vá em busca dos seus sonhos. Bom dia!"
  ]

  const frasesBoaNoite = [
    "Boa noite! Que seus sonhos sejam tranquilos e cheios de paz.",
    "Que a noite traga descanso e serenidade para o seu coração. Boa noite!",
    "Que as estrelas iluminem seus sonhos e a lua guie seu caminho. Boa noite!",
    "Boa noite! Que o silêncio da noite acalme sua alma e prepare você para um novo dia.",
    "Que o sono traga descanso e a manhã traga novas oportunidades. Boa noite!",
    "Boa noite! Que a paz acompanhe seus pensamentos e seus sonhos sejam doces.",
    "Que a noite traga tranquilidade e renove suas energias para o dia seguinte. Boa noite!",
    "Boa noite! Que seus sonhos sejam tão belos quanto as estrelas no céu.",
    "Que a noite traga paz e serenidade para seu coração. Boa noite!",
    "Boa noite! Que o silêncio da noite traga descanso para sua alma.",
    "Que a noite seja de descanso e que amanhã traga novas alegrias. Boa noite!",
    "Boa noite! Que seus sonhos sejam leves e cheios de boas energias.",
    "Que a noite traga consigo a promessa de um novo amanhecer. Boa noite!",
    "Boa noite! Que o descanso renove suas energias para um novo dia cheio de realizações.",
    "Que a noite seja de paz e que o amanhecer traga novas oportunidades. Boa noite!",
    "Boa noite! Que cada estrela no céu brilhe por você esta noite.",
    "Que a noite seja de descanso e que amanhã seja repleto de alegrias. Boa noite!",
    "Boa noite! Que seus sonhos sejam coloridos e cheios de felicidade.",
    "Que a noite traga calma e tranquilidade para o seu coração. Boa noite!",
    "Boa noite! Que o silêncio da noite traga a paz que você precisa.",
    "Que a noite seja de descanso e que o amanhecer traga boas notícias. Boa noite!",
    "Boa noite! Que seus sonhos sejam doces como o mel.",
    "Que a noite traga serenidade e prepare você para um novo dia. Boa noite!",
    "Boa noite! Que o sono seja reparador e os sonhos sejam encantadores.",
    "Que a noite traga consigo a promessa de um amanhã repleto de realizações. Boa noite!",
    "Boa noite! Que a paz habite em seu coração durante toda a noite.",
    "Que a noite traga descanso e prepare você para um novo amanhecer cheio de oportunidades. Boa noite!",
    "Boa noite! Que cada estrela no céu seja um desejo realizado.",
    "Que a noite seja de paz e os sonhos sejam fontes de inspiração. Boa noite!",
    "Boa noite! Que o silêncio da noite acalme sua alma e renove suas energias.",
    "Que a noite traga tranquilidade e o amanhecer traga alegrias. Boa noite!",
    "Boa noite! Que seus sonhos sejam o começo de uma bela realidade.",
    "Que a noite traga consigo a promessa de um futuro brilhante. Boa noite!",
    "Boa noite! Que o descanso traga energia para enfrentar um novo dia com determinação.",
    "Que a noite seja de serenidade e o amanhecer traga novas oportunidades. Boa noite!",
    "Boa noite! Que cada estrela no céu seja um motivo para sorrir.",
    "Que a noite traga paz e alegria para o seu coração. Boa noite!",
    "Boa noite! Que o silêncio da noite traga tranquilidade para sua alma.",
    "Que a noite seja de descanso e o amanhecer traga realizações. Boa noite!",
    "Boa noite! Que seus sonhos sejam como jardins floridos de felicidade.",
    "Que a noite traga consigo a promessa de um novo começo. Boa noite!",
    "Boa noite! Que o sono seja tranquilo e os sonhos sejam inspiradores.",
    "Que a noite traga paz e serenidade para o seu coração. Boa noite!",
    "Boa noite! Que o silêncio da noite acalme sua alma e prepare você para um novo dia cheio de oportunidades.",
    "Que a noite traga descanso e a manhã traga novas alegrias. Boa noite!",
    "Boa noite! Que seus sonhos sejam leves e cheios de paz.",
    "Que a noite traga serenidade e renove suas energias para o dia seguinte. Boa noite!",
    "Boa noite! Que cada estrela no céu brilhe por você esta noite.",
    "Que a noite seja de descanso e que amanhã seja repleto de alegrias. Boa noite!",
    "Boa noite! Que seus sonhos sejam coloridos e cheios de felicidade.",
    "Que a noite traga calma e tranquilidade para o seu coração. Boa noite!",
    "Boa noite! Que o silêncio da noite traga a paz que você precisa.",
    "Que a noite seja de descanso e que o amanhecer traga boas notícias. Boa noite!",
    "Boa noite! Que seus sonhos sejam doces como o mel.",
    "Que a noite traga serenidade e prepare você para um novo dia. Boa noite!"
  ]
  
  const mensagensBiblicas = [
    "O Senhor é o meu pastor; nada me faltará. - Salmo 23:1",
    "Porque eu sei que o meu Redentor vive e por fim se levantará sobre a terra. - Jó 19:25",
    "Tudo posso naquele que me fortalece. - Filipenses 4:13",
    "O Senhor é o meu refúgio e a minha fortaleza, o meu Deus, em quem confio. - Salmo 91:2",
    "Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade. - Salmo 46:1",
    "Bem-aventurado o homem que confia no Senhor e cuja esperança é o Senhor. - Jeremias 17:7",
    "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha. - 1 Coríntios 13:4",
    "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento. - Provérbios 3:5",
    "Vinde a mim, todos os que estão cansados e sobrecarregados, e eu vos aliviarei. - Mateus 11:28",
    "Porque para Deus nada é impossível. - Lucas 1:37",
    "O Senhor é a minha luz e a minha salvação; de quem terei temor? O Senhor é o meu forte refúgio; de quem terei medo? - Salmo 27:1",
    "O meu mandamento é este: Amem-se uns aos outros como eu os amei. - João 15:12",
    "O Senhor te abençoe e te guarde; o Senhor faça resplandecer o seu rosto sobre ti e te conceda graça; o Senhor volte para ti o seu rosto e te dê paz. - Números 6:24-26",
    "O temor do Senhor é o princípio do saber, mas os loucos desprezam a sabedoria e o ensino. - Provérbios 1:7",
    "No mundo, vocês terão aflições; contudo, tenham ânimo! Eu venci o mundo. - João 16:33",
    "O justo passa por muitas adversidades, mas o Senhor o livra de todas. - Salmo 34:19",
    "Mas os que esperam no Senhor renovam as suas forças. Voam alto como águias; correm e não ficam exaustos, andam e não se cansam. - Isaías 40:31",
    "Porque sou eu que conheço os planos que tenho para vocês', diz o Senhor, 'planos de fazê-los prosperar e não de lhes causar dano, planos de dar-lhes esperança e um futuro'. - Jeremias 29:11",
    "Ainda que eu passe por angústias, tu me preservas a vida da ira dos meus inimigos; tu estendes a tua mão direita e me livras. - Salmo 138:7",
    "O meu mandamento é este: Amem-se uns aos outros como eu os amei. - João 15:12",
    "O Senhor te abençoe e te guarde; o Senhor faça resplandecer o seu rosto sobre ti e te conceda graça; o Senhor volte para ti o seu rosto e te dê paz. - Números 6:24-26",
    "O temor do Senhor é o princípio do saber, mas os loucos desprezam a sabedoria e o ensino. - Provérbios 1:7",
    "O justo passa por muitas adversidades, mas o Senhor o livra de todas. - Salmo 34:19",
    "Mas os que esperam no Senhor renovam as suas forças. Voam alto como águias; correm e não ficam exaustos, andam e não se cansam. - Isaías 40:31",
    "Porque para Deus nada é impossível. - Lucas 1:37",
    "O Senhor é o meu pastor; nada me faltará. - Salmo 23:1",
    "Ele cura os de coração quebrantado e cuida das suas feridas. - Salmo 147:3",
    "O Senhor está perto de todos os que o invocam, de todos os que o invocam com sinceridade. - Salmo 145:18",
    "O Senhor é bom, um refúgio em tempos de angústia. Ele protege os que nele confiam. - Naum 1:7",
    "Aquele que tem os meus mandamentos e lhes obedece, esse é o que me ama. Aquele que me ama será amado por meu Pai, e eu também o amarei e me revelarei a ele. - João 14:21",
    "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e o Deus de toda consolação, que nos consola em todas as nossas tribulações, para que, com a consolação que recebemos de Deus, possamos consolar os que estão passando por tribulações. - 2 Coríntios 1:3-4",
    "Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade, mansidão e domínio próprio. Contra essas coisas não há lei. - Gálatas 5:22-23",
    "Deus é o nosso refúgio e a nossa fortaleza, auxílio sempre presente na adversidade. - Salmo 46:1",
    "Bem-aventurado o homem que confia no Senhor e cuja esperança é o Senhor. - Jeremias 17:7",
    "Bendito seja o Deus e Pai de nosso Senhor Jesus Cristo, o Pai das misericórdias e o Deus de toda consolação, que nos consola em todas as nossas tribulações, para que, com a consolação que recebemos de Deus, possamos consolar os que estão passando por tribulações. - 2 Coríntios 1:3-4",
    "Mas o fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade, mansidão e domínio próprio. Contra essas coisas não há lei. - Gálatas 5:22-23",
    "Vinde a mim, todos os que estão cansados e sobrecarregados, e eu vos aliviarei. - Mateus 11:28",
    "O Senhor é o meu refúgio e a minha fortaleza, o meu Deus, em quem confio. - Salmo 91:2",
    "Aquietai-vos e sabei que eu sou Deus; sou exaltado entre as nações, sou exaltado na terra. - Salmo 46:10",
    "Eu é que sei que pensamentos tenho a vosso respeito, diz o Senhor; pensamentos de paz e não de mal, para vos dar o fim que desejais. - Jeremias 29:11",
    "Mas, como está escrito: Nem olhos viram, nem ouvidos ouviram, nem jamais penetrou em coração humano o que Deus tem preparado para aqueles que o amam. - 1 Coríntios 2:9",
    "O Senhor está perto de todos os que o invocam, de todos os que o invocam com sinceridade. - Salmo 145:18",
    "O Senhor é bom, um refúgio em tempos de angústia. Ele protege os que nele confiam. - Naum 1:7",
    "Aquele que tem os meus mandamentos e lhes obedece, esse é o que me ama. Aquele que me ama será amado por meu Pai, e eu também o amarei e me revelarei a ele. - João 14:21",
    "O Senhor é o meu pastor; nada me faltará. - Salmo 23:1",
    "Ele cura os de coração quebrantado e cuida das suas feridas. - Salmo 147:3",
    "O Senhor está perto de todos os que o invocam, de todos os que o invocam com sinceridade. - Salmo 145:18",
    "O Senhor é bom, um refúgio em tempos de angústia. Ele protege os que nele confiam. - Naum 1:7",
    "Aquele que tem os meus mandamentos e lhes obedece, esse é o que me ama. Aquele que me ama será amado por meu Pai, e eu também o amarei e me revelarei a ele. - João 14:21",
  ]
  
 
  
  

export const frases: Frases = [
    {
      id: 1,
      categoria: "motivacional",
      selected: false,
      frases: frasesMotivacionais
    },
    {
      id: 2,
      categoria: "bom dia",
      selected: false,
      frases: frasesBomDia
    },
    {
      id: 3,
      categoria: "boa noite",
      selected: false,
      frases: frasesBoaNoite
    },
    {
        id: 4,
        categoria: "bíblia",
        selected: false,
        frases: mensagensBiblicas
      }
  ]